{% set name = "mammos" %}
{% set version = "0.11.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mammos-{{ version }}.tar.gz
  sha256: 961f55783951d3e21461eecaa2c7c86324e6cbfa1f67182d97fbd8eba63a3666

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - mammos-ai ==0.2.0
    - mammos-analysis ==0.4.0
    - mammos-dft ==0.4.1
    - mammos-entity ==0.11.1
    - mammos-mumag ==0.10.1
    - mammos-spindynamics ==0.3.1
    - mammos-units ==0.3.2

test:
  imports:
    - mammos
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://mammos-project.github.io
  summary: A multiphyscis simulation suite for magnetic materials.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrea-petrocchi
    - fangohr
    - lang-m
    - swapneelap
