{% set name = "mammos" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mammos-{{ version }}.tar.gz
  sha256: ede01a802c5713ca1e9e6f741447cf78b5878efe55c25698f752bafa2dfd1fd5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - mammos
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://mammos-project.github.io
  summary: A multiphyscis simulation suite for magnetic materials.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrea-petrocchi
    - fangohr
    - lang-m
    - swapneelap
