{% set name = "mammos" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mammos-{{ version }}.tar.gz
  sha256: dcb1124ad442ae9f3660359ca4909d9d997603c856f757cc8f49024d2d6541a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8

test:
  imports:
    - mammos
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://mammos-project.github.io
  summary: A multiphyscis simulation suite for magnetic materials.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swapneelap
