{% set name = "mammos" %}
{% set version = "0.12.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mammos-{{ version }}.tar.gz
  sha256: 63b6932c4be9cb3d11c78850fa5429ffe30099e71976423935d8a831851ed9f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - mammos-ai ==0.2.0
    - mammos-analysis ==0.5.0
    - mammos-dft ==0.5.0
    - mammos-entity ==0.12.0
    - mammos-mumag ==0.11.0
    - mammos-spindynamics ==0.4.0
    - mammos-units ==0.3.2

test:
  imports:
    - mammos
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://mammos-project.github.io
  doc_url: https://mammos-project.github.io/mammos
  dev_url: https://github.com/MaMMoS-project/mammos
  summary: A multiphysics simulation suite for magnetic materials.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrea-petrocchi
    - fangohr
    - lang-m
    - swapneelap
